/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wang_appupdate_util_PatchUtil */

#ifndef _Included_com_wang_appupdate_util_PatchUtil
#define _Included_com_wang_appupdate_util_PatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wang_appupdate_util_PatchUtil
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wang_appupdate_util_PatchUtil_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_wang_appupdate_util_PatchUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wang_appupdate_util_PatchUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
